name: Daily Slack

on:
  workflow_dispatch: # lets you trigger it manually
  schedule:
    - cron: "15 16 * * *" # 9:15 AM Central (adjust below if needed)

jobs:
  run-daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SHEETS_CONFIG_JSON: ${{ secrets.SHEETS_CONFIG_JSON }}
        run: python dailynumbers.py
